// Auto-generated by QualiVerse Performance Testing agent.
import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  vus: 10,
  duration: '30s',
  thresholds: {
    http_req_duration: ['p(95)<800'],
    // Without this, k6 exits 0 (our code reports "passed") even if every
    // single request fails — check() failures alone don't affect the exit
    // code, only a breached threshold does.
    checks: ['rate==1.0'],
  },
};

export default function () {
  const res = http.get('http://localhost:8085');
  check(res, { 'status is 200': (r) => r.status === 200 });
  sleep(1);
}
// Test case: Dashboard Redirect on Successful Login (Performance)
// Expected result: All users are redirected to the dashboard.
