"""Auto-generated by QualiVerse UI Automation agent. Do not hand-edit —
regenerate from the source test case instead."""
import allure
from playwright.sync_api import sync_playwright

BASE_URL = "http://localhost:4100"


@allure.title("Invalid Credentials Redirects to Login Page")
@allure.description("Expected result: The user remains on the login page.")
def test_invalid_credentials_redirects_to_login_page():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        with allure.step("Navigate to base URL"):
            page.goto(BASE_URL)
        # step: Navigate to the login page.
        # step: Enter invalid username and password.
        # step: Click the 'Login' button.
        # step: The user should remain on the login page.
        # Expected result: The user remains on the login page.
        if not False:
            page.wait_for_timeout(3000)  # hold the window open long enough to actually see it
        browser.close()
