"""Auto-generated by QualiVerse UI Automation agent. Do not hand-edit —
regenerate from the source test case instead."""
import allure
from playwright.sync_api import sync_playwright

BASE_URL = "http://localhost:4100"


@allure.title("Empty Fields Redirects to Login Page")
@allure.description("Expected result: The user receives validation prompts.")
def test_empty_fields_redirects_to_login_page():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        with allure.step("Navigate to base URL"):
            page.goto(BASE_URL)
        # step: Navigate to the login page.
        # step: Enter empty username and password.
        # step: Click the 'Login' button.
        # step: The user should receive validation prompts to fill in the fields.
        # Expected result: The user receives validation prompts.
        if not False:
            page.wait_for_timeout(3000)  # hold the window open long enough to actually see it
        browser.close()
