"""Auto-generated by QualiVerse UI Automation agent. Do not hand-edit —
regenerate from the source test case instead."""
import allure
from playwright.sync_api import sync_playwright

BASE_URL = "http://localhost:4100"


@allure.title("Dashboard Redirect on Successful Login")
@allure.description("Expected result: The user is redirected to the dashboard.")
def test_dashboard_redirect_on_successful_login():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        page = browser.new_page()
        with allure.step("Navigate to base URL"):
            page.goto(BASE_URL)
        # step: Navigate to the login page.
        # step: Enter valid username and password.
        # step: Click the 'Login' button.
        # step: The user should be redirected to the dashboard.
        # Expected result: The user is redirected to the dashboard.
        if not False:
            page.wait_for_timeout(3000)  # hold the window open long enough to actually see it
        browser.close()
